### ISSUE TITLE
Wrong domain is already being monitored error

### ISSUE THREAD

**Issue by gfrooo1989** [yassineaboukir/sublert#1]
Hey,

First of all thanks for the tool. There is a small bug in the app in how domains are check if they are already monitored.
If the second domain you want to add is part of the last added domain, it will be considered already monitored, witch is false.

Ex :

```
sublert.py -u uber.com
```
 -> uber.com will be monitored -> good

```
sublert.py -u ber.com
```
 -> ber.com is already monitored -> small bug here, ber.com is not monitored, but because it's the last part of uber it is considered monitored

**Comment by yassineaboukir** [comment]
Hi,

That's good catch! I just resolved the issue now. Let me know if it's still reproducible.

Thanks!
