### ISSUE TITLE
A grammatical error

### ISSUE THREAD

**Issue by admintony** [yassineaboukir/sublert#10]
Your code is：

`from tld import get_fld`

but tld do not have get_fld

The correct code is：

`from tld import get_tld`

and then you shuld modify all of " get_tld "

**Comment by yassineaboukir** [comment]
Hi,

tld modules does have `get_fld`. Please refer to https://pypi.org/project/tld/

Did you receive an error while running the tool?

Regards.

**Comment by yassineaboukir** [comment]
Closing as false positive. If you're running into issues please update the ticket and will follow-up. Thank you!

**Comment by surajpkhetani** [comment]
Hi @yassineaboukir `from tld.utils import update_tld_names` gives error. By changing to `from tld.utils import get_tld_names` the script works.
