### ISSUE TITLE
Not getting updates 

### ISSUE THREAD

**Issue by jaikishantulswani** [yassineaboukir/sublert#11]
Hello @yassineaboukir ,

Setup sublert on 27th March to monitor 20+ domains but till today I am getting the same notification "Couldn't find any new valid subdomain" even the "output" folder is not showing updated files of fetched domains as it still showing the last updated date "Mar 27", am I doing anything wrong ?

Thank You

**Comment by yassineaboukir** [comment]
Hi @jaikishantulswani,

It might be true that Sublert couldn't identify any new subdomain deployed by the monitored organizations but it also could be a bug, would you make sure to update your repository to use the latest version `1.7.4`? Then just copy the `domains.txt` file from the old directory to the new repo and run Sublert again.

Keep me updated.

Regards.

**Comment by jaikishantulswani** [comment]
Hello @yassineaboukir ,
Thank you for your reply. It Works :+1:

**Comment by jaikishantulswani** [comment]
Hello @yassineaboukir ,

Yesterday it works after as you suggested but now today morning it again showing the same notification "Couldn't find any new valid subdomain"  and not updating the output folder too, even after setting up the sublert again :(

**Comment by jaikishantulswani** [comment]
Now getting the error in log `There was an error opening one of the files: example.com.txt or example.com_tmp.txt`  with the notification in monitoring `We couldn't find any new valid subdomains`

**Comment by jaikishantulswani** [comment]
Hello @yassineaboukir ,
Any suggestion on this as I am still facing this issue.
