### ISSUE TITLE
Adding additional flag to ignore show domains banner

### ISSUE THREAD

**Issue by 0xaud** [yassineaboukir/sublert#12]
Hi,

Because of the banner we can't really do cat domains | read.......sublert.py $domain -u as the banner pop-ups after scan.

It's hectic to add bunch of domains manually.

**Comment by yassineaboukir** [comment]
Hi,

Sublert doesn't support batch importing of domains yet but it's in the roadmap. I'll also add an option to skip the message whether you want to display the list of subdomains or not when you add a new domain to monitor.

Thank you for bringing it up.

**Comment by yassineaboukir** [comment]
On the other hand, you can add a bunch of domains by manually editing `domains.txt` but be careful of the newline character when doing so.

**Comment by yassineaboukir** [comment]
Hi,

This is now fixed. You can append "-q true" to your command to skip the user input question.

Thanks!
