### ISSUE TITLE
Question: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pooja2508** [yassineaboukir/sublert#13]
I'm trying to use sublert but its showing following error, have followed the steps (but instead of VPS, i'm running from a ubuntu box), could you please suggest how to fix this error ? 

root@UbuntuNTP2:~/sublert# python sublert.py -u google.com

                   _____       __    __          __
                  / ___/__  __/ /_  / /__  _____/ /_
                  \__ \/ / / / __ \/ / _ \/ ___/ __/
                 ___/ / /_/ / /_/ / /  __/ /  / /_
                /____/\__,_/_.___/_/\___/_/   \__/
    
Traceback (most recent call last):
  File "sublert.py", line 439, in <module>
    multithreading(parse_args().threads)
  File "sublert.py", line 418, in multithreading
    adding_new_domain(domain_to_monitor)
  File "sublert.py", line 228, in adding_new_domain
    for subdomain in response:
TypeError: 'NoneType' object is not iterable
root@UbuntuNTP2:~/sublert# python -V
Python 2.7.12
root@UbuntuNTP2:~/sublert#

**Comment by yassineaboukir** [comment]
Hi,

I think Sublert failed to fetch the subdomains of `google.com`. I think I'll need to add an exception to handle this case but can you to run it again and see if you receive any error logged to your slack channel?

**Comment by pooja2508** [comment]
Thankyou for your reply. 
I retried it but getting the same error & there are no error logged in slack channel as well : 
root@UbuntuNTP2:~/sublert#  python sublert.py -u paypal.com

                   _____       __    __          __
                  / ___/__  __/ /_  / /__  _____/ /_
                  \__ \/ / / / __ \/ / _ \/ ___/ __/
                 ___/ / /_/ / /_/ / /  __/ /  / /_
                /____/\__,_/_.___/_/\___/_/   \__/
    
Traceback (most recent call last):
  File "sublert.py", line 439, in <module>
    multithreading(parse_args().threads)
  File "sublert.py", line 418, in multithreading
    adding_new_domain(domain_to_monitor)
  File "sublert.py", line 228, in adding_new_domain
    for subdomain in response:
TypeError: 'NoneType' object is not iterable
root@UbuntuNTP2:~/sublert#  python sublert.py -u amazon.com

                   _____       __    __          __
                  / ___/__  __/ /_  / /__  _____/ /_
                  \__ \/ / / / __ \/ / _ \/ ___/ __/
                 ___/ / /_/ / /_/ / /  __/ /  / /_
                /____/\__,_/_.___/_/\___/_/   \__/
    
Traceback (most recent call last):
  File "sublert.py", line 439, in <module>
    multithreading(parse_args().threads)
  File "sublert.py", line 418, in multithreading
    adding_new_domain(domain_to_monitor)
  File "sublert.py", line 228, in adding_new_domain
    for subdomain in response:
TypeError: 'NoneType' object is not iterable
root@UbuntuNTP2:~/sublert# 

However i can do a curl to slack channel with same webhoook url. 
Could you please suggest if I'm missing anything while executing the script ?

**Comment by pooja2508** [comment]
Have tried running script using python3 also, but no luck:
root@slave-ubuntu-187:/var/TOOLS/sublert# python3 sublert.py -u paypal.com

                   _____       __    __          __
                  / ___/__  __/ /_  / /__  _____/ /_
                  \__ \/ / / / __ \/ / _ \/ ___/ __/
                 ___/ / /_/ / /_/ / /  __/ /  / /_
                /____/\__,_/_.___/_/\___/_/   \__/
    
             Author: Yassine Aboukir (@yassineaboukir)
                           Version: 1.4.7
Traceback (most recent call last):
  File "sublert.py", line 440, in <module>
    multithreading(parse_args().threads)
  File "sublert.py", line 419, in multithreading
    adding_new_domain(domain_to_monitor)
  File "sublert.py", line 229, in adding_new_domain
    for subdomain in response:
TypeError: 'NoneType' object is not iterable
root@slave-ubuntu-187:/var/TOOLS/sublert#

**Comment by pooja2508** [comment]
Hi @yassineaboukir, Have you got a chance to look into this query & suggest how shall i proceed further with this ? I have tried on 2-3 setups with python2/3 and unfortunately have received the same error.

**Comment by yassineaboukir** [comment]
Hi,

I was unfortunately unable to reproduce the issue and might be caused by your Python environment instead.

Regards.
