### ISSUE TITLE
Slack.com keeps showing that we can't find any new valid subfields.

### ISSUE THREAD

**Issue by MaxSecurity** [yassineaboukir/sublert#14]
What's going on here

**Comment by yassineaboukir** [comment]
Can you please check `https://crt.sh/?q=%25.<monitored_domain>` (after replacing <monitored_domain>) and see if new subdomains were deployed after you started using Sublert?

**Comment by MaxSecurity** [comment]
There is still no

**Comment by yassineaboukir** [comment]
If there aren't any new subdomains, that means Sublert is indeed right. Anything I am missing?

**Comment by yassineaboukir** [comment]
Closing.
