### ISSUE TITLE
Slack going berserk 

### ISSUE THREAD

**Issue by sumgr0** [yassineaboukir/sublert#15]
I’ve had the setup on my Digitalocean VPS since mid March, which was working great. 

Since yesterday morning my Slack notifications for new sub-domains is getting bombarded. 

It seems like to be running the command in the loop and notifying of all the sub-domains instead of the refresh. 

I’ve since tried to do a fresh install of the app along with fresh app creation and web-hook in slack, but it still persists. 

Anything I can check to rectify at my end?

Thanks

**Comment by yassineaboukir** [comment]
Hey! I'd suggest to copy the `domains.txt` to somewhere safe, then reset everything by running `$ python sublert.py -m`. Afterwards, place back the `domains.txt` file to Sublert directory and run the tool as usual. 

Let me know if that fixes the issue for you.

**Comment by sumgr0** [comment]
Thanks for the solution. 

So I copied my domains.txt file and reset the app. However, when importing the same domains.txt, there were errors for few domains, which I had to manually delete and add them again.

Also, since the slack going crazy, things haven't been as smooth. Like the cronjob not working regularly and notifications not coming through, errors with app not able to access the db etc.

I might try removing the app from VPS and crontab and then following the same process to setup again. Hope that would resolve the issue.

If you have a better solution, I'd really like to hear it. Thanks

**Comment by spaceraccoon** [comment]
@sumgro As per #19 I believe it has to do with the default number of threads (20) which may overwhelm lower-specced boxes. Try setting `-t 4` or similar.

**Comment by sumgr0** [comment]
Hey @spaceraccoon, thanks for the suggestion. I’ve edited the thread to 10 now and shall test it for a day. 
Will update the findings later. 
Cheers!!

**Comment by ngkogkos** [comment]
Any news on this @sumgro ?

**Comment by sumgr0** [comment]
> Any news on this @sumgro ?

Sorted this out by setting the thread value to 2 and that seems to have resolved it.

Are you also experiencing the same?

**Comment by ngkogkos** [comment]
I only had this with yahoo.com, but I am testing it on other domains now and no issues.

**Comment by yassineaboukir** [comment]
I have adjusted the threads number in the code as well. Thanks!
