### ISSUE TITLE
Unable to connect to the database. We will attempt to use the API instead

### ISSUE THREAD

**Issue by jaikishantulswani** [yassineaboukir/sublert#17]
Getting this even after resetting sublert:

`Unable to connect to the database. We will attempt to use the API instead`

**Comment by manuelbua** [comment]
@jaikishantulswani, it's not a sublert problem but it looks like `crt.sh` is not accepting connections on port `5432` for some time now, not sure what's happening but i'm hitting this with my tools too.

**Comment by jaikishantulswani** [comment]
@manuelbua @yassineaboukir but by running https://crt.sh/?q=%.example.com&output=json directly on a web browser showing results.
Can you please let me know why the same is not performing in sublert

**Comment by JoshuaMart** [comment]
Hi,
I have the same error than @jaikishantulswani if I add more than 6 domains to sublert.
Thank's

**Comment by vasilerevnic** [comment]
Also have the same issue. Seems like it's not switching to the API when DB connection is not available.

**Comment by PjMpire** [comment]
@yassineboukir im also having the same issue when using a large list of domains. 

Script seems to have broken as im also getting rate limiting errors.

![image](https://user-images.githubusercontent.com/25329113/64222795-4ef5f100-cec9-11e9-9a60-4d632fd7ccf9.png)

**Comment by yassineaboukir** [comment]
Hi,

This should now be fixed. Please clone the new repo.

Thanks!
