### ISSUE TITLE
Unable to connect to the database.

### ISSUE THREAD

**Issue by sususukkk** [yassineaboukir/sublert#18]
Unable to connect to the database. 
I have this problem

**Comment by manuelbua** [comment]
@woadsl1234 it looks like `crt.sh` is not accepting connections on port `5432` for some time now, not sure what's happening but i'm hitting this with my tools too.

**Comment by yassineaboukir** [comment]
Hi, 

This has already been filed in #17 which I'll be working on fixing soon. Thanks for filing the ticket nevertheless.

Regards.
