### ISSUE TITLE
Default Number of Threads

### ISSUE THREAD

**Issue by spaceraccoon** [yassineaboukir/sublert#19]
Hi!

It seems a couple of people have been getting `Unable to connect to the database. We will attempt to use the API instead.` I looked into it more and it seems that smaller/lower-specced boxes (like Linode's Nanode or EC2 Micro) can't handle the default number of threads (20) and eventually timeout while querying crt.sh, leading to this error. You might want to set the default to something lower (10 worked) as the baseline. I've been getting around it by setting `-t` manually.

Thanks for your work!

**Comment by yassineaboukir** [comment]
Hi,

Apologies for the delay. I haven't had much time to look into the issue but appreciate your suggestion. I'll aim to fix this along with other minor issues by next weekend, hopefully. 

Cheers!

**Comment by yassineaboukir** [comment]
Hi,

Thanks for the good recomendation. The initial number was inded a bit high so I made sure to adjust the default threads to 10 but I think this might not fix the underlying problem. 

Regards.
