### ISSUE TITLE
Feature request: search for any string 

### ISSUE THREAD

**Issue by michbsd** [yassineaboukir/sublert#24]
Hi,

Fist off, thanks for making this tool!

As a feature request, it would be great to search for any string (e.g . “Amazon” to see a list of all certs generated for a domain containing the string “Amazon”). 
This would allow you to use the tool for phishing monitoring as well. 

Thanks 🙏

**Comment by yassineaboukir** [comment]
Hi,

Thanks for filing this issue. The tool was mainly designed for subdomains monitoring but if you want to monitor phishing attempts, you can use Facebook transparency which was built for that purpose https://developers.facebook.com/docs/certificate-transparency

Regards.
