### ISSUE TITLE
a bug in some special situation

### ISSUE THREAD

**Issue by onkyoworm** [yassineaboukir/sublert#29]
when i run your script like
`python sublert.py -u nearme.com`
it throw me a error 
`Traceback (most recent call last):
  File "sublert.py", line 440, in <module>
    multithreading(parse_args().threads)
  File "sublert.py", line 419, in multithreading
    adding_new_domain(domain_to_monitor)
  File "sublert.py", line 229, in adding_new_domain
    for subdomain in response:
TypeError: 'NoneType' object is not iterable
` 
At first i think this error shows because the script cannot find any subdomain of `nearme.com`
But later, i found `[!] Unfortunately, we couldn't find any subdomain for oppostore.com` maybe the correct output of finding no subdomains.
So i doubt why the this error show?
After surfing the `nearme.com`, i found it for sale
Clearly, this error shows because this domain are not using
Hope you fix it well
Sincerely

**Comment by yassineaboukir** [comment]
Hi,

I was able to reproduce the issue and will work on fixing it. Thanks for flagging!

Regards.

**Comment by yassineaboukir** [comment]
This commit https://github.com/yassineaboukir/sublert/commit/d1782bace1b1b5e67a6237f14ae989805850360d should hopefully address the issue. Clone a new version and let lme know if it's still reproducible.
