### ISSUE TITLE
some bug about require package

### ISSUE THREAD

**Issue by onkyoworm** [yassineaboukir/sublert#30]
i change my python environment last day，unfortunately some bug shows when i run sublert.py
the error is about the **tld** package
`Traceback (most recent call last):
  File "sublert.py", line 15, in <module>
    from tld import get_fld
ImportError: cannot import name 'get_fld'
`
and i check the version of it，`Successfully uninstalled tld-0.7.9`
and reinstall the latest version `Successfully installed tld-0.9.6`
And i found the requirements.txt don't point out the lastest version of it
So i report =.=
Sincerely

**Comment by yassineaboukir** [comment]
Hi,

Thanks for reporting. The following commit: https://github.com/yassineaboukir/sublert/commit/23edf2dd1d9c040024fd7cedf3104b8622713fd4 should fix the issue.

Regards.
