### ISSUE TITLE
invalid syntax with webhook url

### ISSUE THREAD

**Issue by jamatou** [yassineaboukir/sublert#40]
Hi,
I follow all instruction and when i run python sublert.py -u paypal.com , i got error with webhook. invalid syntax.please see attachment.
Thanks for you reply.
Jamshid
![error](https://user-images.githubusercontent.com/45011146/120519255-b3155400-c3d2-11eb-84a1-f6c2fa03c731.PNG)

**Comment by yassineaboukir** [comment]
Make sure the webhook is between quotes in the config file.

**Comment by jamatou** [comment]
Thanks. As always perfect .
