### ISSUE TITLE
[Bug] Iterating the record names

### ISSUE THREAD

**Issue by arbazkiraak** [yassineaboukir/sublert#5]
Hi,

```python
                        for i in dns_result[subdomain]["A"]:
                            data = "```A : {}```".f
```

> There's a bug at line `366` and `370` 

Which is iterating word by word of `CNAME` and `A` records: and posting the data to `slack`.

**Comment by yassineaboukir** [comment]
Hi,

I haven't been able to replicate this issue yet but still looking into it. Thank you for flagging!

**Comment by yassineaboukir** [comment]
Hi,

I am unable to replicate the issue. It used to be a bug but the following commit resolved it https://github.com/yassineaboukir/sublert/commit/7d480b6eea28ff4613648b763305db7907d3ba1f#diff-198435d23e8d0b20783306dcebcb0e25R333

(Line 333 and 334)

Make sure you clone the latest version. See:

![sublert](https://i.imgur.com/xjshgzj.png)

I am closing this issue in the meantime. Thanks!
